name: Compile

# Controls when the action will run. 
on:
#   Triggers the workflow on push events but only for the main branch
#  push:
#    branches: [ batch ]

   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
# Define default defconfig here
  CONFIG : mi8937_defconfig
  device : mi8937
  repo_link: https://github.com/mi-msm8937/android_kernel_xiaomi_msm8937

jobs:
  build:
    runs-on: ubuntu-20.04
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Cleaning Up Runner
        uses: rokibhasansagar/slimhub_actions@main

      # Setup the environment
      - name: Environment Setup
        run: |
          bash -c "$(wget -O- https://github.com/aryankaran/kernel_builder/raw/batch/.github/workflows/setup.sh)"

      # Compile the kernel and send
      - name: Compile Kernel and upload to Telegram
        env:
          BOT_TOKEN : ${{secrets.BOT_TOKEN}}
          CHAT_ID : ${{secrets.CHAT_ID}}
        run: |
          bash -c "$(wget -O- https://github.com/aryankaran/kernel_builder/raw/batch/.github/workflows/compile.sh)"
