name: Compile

# Controls when the action will run. 
on:
 # Triggers the workflow on push events but only for the batch branch
 # push:
   # branches: [ batch ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      CONFIG_INPUT:
        description: 'List of defconfigs to build'
        required: true
        default: 'mi8937_defconfig'
      device_INPUT:
        description: 'Device codename'
        required: true
        default: 'mi8937'
      repo_link_INPUT:
        description: 'Repo Link'
        required: true
        default: 'https://github.com/mi-msm8937/android_kernel_xiaomi_msm8937'

env:
  CONFIG : ${{ github.event.inputs.CONFIG_INPUT }}
  device : ${{ github.event.inputs.device_INPUT }}
  repo_link: ${{ github.event.inputs.repo_link_INPUT }}

jobs:
  build:
    runs-on: ubuntu-20.04
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: CleanUp Runner
        uses: rokibhasansagar/slimhub_actions@main

      # Setup the environment
      - name: Environment Setup
        run: |
          bash -c "$(wget -O- https://github.com/aryankaran/kernel_builder/raw/batch/.github/workflows/setup.sh)"

      # Compile the kernel and send
      - name: Compile Kernel and upload to Telegram
        env:
          BOT_TOKEN : ${{secrets.BOT_TOKEN}}
          CHAT_ID : ${{secrets.CHAT_ID}}
        run: |
          bash -c "$(wget -O- https://github.com/aryankaran/kernel_builder/raw/batch/.github/workflows/compile.sh)"
