name: Compile

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ rova ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
# Define default defconfig here
  DEFCONFIG : tiare_defconfig
  device : tiare
  repo : github.com/aryan-karan/platform_kernel_xiaomi_msm8917
  reference : lineage-18.0

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clone the source
        uses: actions/checkout@v2
        with:
          repository: aryan-karan/platform_kernel_xiaomi_msm8917
          ref: lineage-18.0

      # Setup the environment
      - name: Setup
        run: |
          bash -c "$(wget -O- https://github.com/aryankaran/kernel_builder/raw/rova/.github/workflows/setup.sh)"

      # Compile the kernel
      - name: Compile
        run: |
          bash -c "$(wget -O- https://github.com/aryankaran/kernel_builder/raw/rova/.github/workflows/compile.sh)"

      # Make zip and Send it to telegram
      - name: Make zip and send
        env:
          BOT_TOKEN : ${{secrets.BOT_TOKEN}}
          CHAT_ID : ${{secrets.CHAT_ID}}
        run: |
          bash -c "$(wget -O- https://github.com/aryankaran/kernel_builder/raw/rova/.github/workflows/send2tg.sh)"
